DROP TABLE IF EXISTS lab15_articles;

create table lab15_articles(
  artid int not null auto_increment,
  title varchar(1000),
  body TEXT,
  primary key(artid)
);

insert into lab15_articles values (1, 'Apirana Turupa Ngata', 'One of 15 children, Ngata was born in Te Araroa (then called Kawakawa), a small coastal town about 175 kilometres north of Gisborne, New Zealand.[1] His iwi was Ngāti Porou. His father was Paratene Ngata, a tribal leader and expert in traditional lore, and his mother was Katerina Naki, the daughter of an itinerant Scot, Abel Knox.[2] Ngata was greatly influenced both by his father and by his great-uncle Ropata Wahawaha (who had led loyal kupapa Ngāti Porou forces against their Pai Mārire enemy (commonly known as Hauhau) in the East Cape War and later Te Kooti''s escapees from the Chatham Islands.)[3] Ngata was raised in a Māori environment, speaking the Māori language, but his father also ensured that Ngata learned about the Pākehā world, believing that this understanding would be of benefit to Ngāti Porou.');
insert into lab15_articles values (2, 'Edmund Hillary', 'Sir Edmund Percival Hillary KG ONZ KBE (20 July 1919 – 11 January 2008) was a New Zealand mountaineer, explorer and philanthropist. On 29 May 1953, Hillary and Nepalese Sherpa mountaineer Tenzing Norgay became the first climbers to reach the summit of Mount Everest. They were part of the ninth British expedition to Everest, led by John Hunt. Hillary was named by Time as one of the 100 most influential people of the 20th century. Hillary became interested in mountaineering while in secondary school, making his first major climb in 1939, reaching the summit of Mount Ollivier. He served in the Royal New Zealand Air Force as a navigator during World War II. Prior to the 1953 Everest expedition, Hillary had been part of the British reconnaissance expedition to the mountain in 1951, as well as an unsuccessful attempt to climb Cho Oyu in 1952. As part of the Commonwealth Trans-Antarctic Expedition he reached the South Pole overland in 1958. He subsequently reached the North Pole, making him the first person to reach both poles and summit Everest.\nFollowing his ascent of Everest, Hillary devoted most of his life to helping the Sherpa people of Nepal through the Himalayan Trust, which he founded. Through his efforts, many schools and hospitals were built in Nepal.');
insert into lab15_articles values (3, 'Ernest Rutherford', 'Ernest Rutherford was the son of James Rutherford, a farmer, and his wife Martha Thompson, originally from Hornchurch, Essex, England.[10] James had emigrated to New Zealand from Perth, Scotland, "to raise a little flax and a lot of children". Ernest was born at Brightwater, near Nelson, New Zealand. His first name was mistakenly spelled ''Earnest'' when his birth was registered.[11]');
insert into lab15_articles values (4, 'Kate Sheppard', 'Kate Sheppard was born Catherine Wilson Malcolm in Liverpool, England to Scottish parents Jemima Crawford Souter and Andrew Wilson Malcolm.[4] She generally preferred to spell her given name "Katherine", or abbreviate it to "Kate". She received a good education, and was noted for her intellectual ability and broad knowledge. For a time she lived with her uncle, a minister of the Free Church of Scotland at Nairn.[3] In 1869, several years after her father''s death, Sheppard and her siblings immigrated with their mother to Christchurch, New Zealand. She married Walter Allen Sheppard three years later, and their only child, Douglas, was born on 8 December 1880.[4]');
insert into lab15_articles values (5, 'Kate FooBar', 'Foo bar.');
insert into lab15_articles values (6, 'Wibble Kate', 'Wibble.');
